name: C Build and Test (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install GCC (MinGW)
      run: choco install mingw -y

    - name: Add GCC to PATH
      run: |
        echo "C:\MinGW\bin" >> $GITHUB_PATH

    - name: Build the code
      run: gcc main.c -o myprogram.exe

    - name: Run the program
      run: ./myprogram.exe
